# k -n demo delete -f kubernetes/simple-task.yaml; k -n demo apply -f kubernetes/simple-task.yaml
# tkn -n demo taskrun logs curl-gitea -f
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: curl-gitea
spec:
  params:
    - name: REGISTRY_HOST
      value: "gitea.cnoe.localtest.me:8443"
  taskSpec:
    steps:
      - name: curl-gitea
        image: quay.io/curl/curl:latest
        script: |
          #!/bin/sh
          
          cat /etc/hosts
          cat /etc/resolv.conf
          
          echo "## Curl to the registry host: https://$(params.REGISTRY_HOST)/api/swagger ..."
          curl -v -k https://$(params.REGISTRY_HOST)/api/swagger

      - name: podman-check
        image: quay.io/containers/podman:v5.0.3
        script: |
          #!/bin/sh
          
          echo "Creating a container against daemon host: 10.89.0.1."
          PODMAN_CMD="podman -r --url=tcp://10.89.0.1:2375"
          
          $PODMAN_CMD info
