apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: gitea-server-check
spec:
  taskSpec:
    steps:
      - name: check-ping
        image: busybox # Use a lightweight image like busybox, or you can also use curlimages/curl
        script: |
          #!/bin/sh
          
          cat /etc/hosts
          cat /etc/resolv.conf
          
          echo "## Hack to allow to access: gitea.cnoe.localtest.me"
          echo "127.0.0.1 gitea.cnoe.localtest.me" >> /etc/hosts
          
          echo "## Pinging gitea.cnoe.localtest.me ..."
          ping -c 4 gitea.cnoe.localtest.me
